// Generated by scripts/build-bridge.mjs.
// Source: web/bridge/src/main.js and styles.css.
// Other bridge modules are injected before this entrypoint by the native shells.
(function () {
  "use strict";

  function initCoreStyles() {
    var style = document.getElementById("sl-core-ui-styles");
    if (style) return;

    style = document.createElement("style");
    style.id = "sl-core-ui-styles";
    style.textContent = ".back-button-container-lDB1N svg {\n  filter:\n    drop-shadow(1px 0 0 rgba(15, 15, 25, 0.25))\n    drop-shadow(-1px 0 0 rgba(15, 15, 25, 0.25))\n    drop-shadow(0 1px 0 rgba(15, 15, 25, 0.25))\n    drop-shadow(0 -1px 0 rgba(15, 15, 25, 0.25)) !important;\n}\n\n#sl-speed-hint {\n  position: fixed;\n  top: calc(24px + env(safe-area-inset-top));\n  left: 50%;\n  z-index: 2147483647;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  gap: 7px;\n  box-sizing: border-box;\n  width: 104px;\n  padding: 5px 16px;\n  border-radius: 999px;\n  color: #fff;\n  background: rgba(13, 11, 20, 0.58);\n  backdrop-filter: blur(12px);\n  transform: translateX(-50%);\n  pointer-events: none;\n}\n\n#sl-speed-hint[hidden] {\n  display: none;\n}\n\n.sl-speed-hint-value {\n  font-size: 15px;\n  font-weight: 400;\n  line-height: 1;\n  letter-spacing: 0.02em;\n  font-variant-numeric: tabular-nums;\n}\n\n.sl-speed-hint-icon {\n  width: 16px;\n  height: 8px;\n  color: rgba(189, 164, 255, 0.8);\n  transform: translateY(1px);\n}";
    document.head.appendChild(style);
  }

  var host = window.StremioLightningHost || null;
  var log = window.StremioLightningLogger.bind("bridge.main");

  if (!host) {
    log.error(
      "[StremioLightning] host adapter not available - bridge not loaded",
    );
  } else {
    var ctx = {
      host: host,
      appWindow: host.window,
      webview: host.webview,
      pipFeatureOn: localStorage.getItem("sl-pip-feature") !== "false",
      shellTransport: null,
      initDiscordRpc: function () {},
      initUpdateChecker: function () {},
    };

    log.info("[StremioLightning] Native player mode enabled (libmpv transport)");

    onDomReady(initCoreStyles);

    ctx.shellTransport = initShellTransport(ctx);
    ctx.shellTransport.observeMpvProperties();

    window.StremioEnhancedAPI = window.StremioEnhancedAPI || {};

    initExternalLinks(ctx);
    initShellDetection();
    initBackButton();
    initShortcuts(ctx);
    initPictureInPicture(ctx);
    initDiscordRpcTracker(ctx);
    initUpdateBanner(ctx);

    onWindowLoad(function () {
      ctx.initDiscordRpc();
      ctx.initUpdateChecker();
    });
  }
})();
