// Generated by scripts/build-bridge.mjs.
// Source: web/bridge/src/main.js and styles.css.
// Other bridge modules are injected before this entrypoint by the native shells.
(function () {
  "use strict";

  function initCoreStyles() {
    var style = document.getElementById("sl-core-ui-styles");
    if (style) return;

    style = document.createElement("style");
    style.id = "sl-core-ui-styles";
    style.textContent = ".back-button-container-lDB1N svg {\r\n  filter:\r\n    drop-shadow(1px 0 0 rgba(15, 15, 25, 0.25))\r\n    drop-shadow(-1px 0 0 rgba(15, 15, 25, 0.25))\r\n    drop-shadow(0 1px 0 rgba(15, 15, 25, 0.25))\r\n    drop-shadow(0 -1px 0 rgba(15, 15, 25, 0.25)) !important;\r\n}\r\n\r\n#sl-speed-hint {\r\n  position: fixed;\r\n  top: calc(24px + env(safe-area-inset-top));\r\n  left: 50%;\r\n  z-index: 2147483647;\r\n  display: flex;\r\n  align-items: center;\r\n  justify-content: center;\r\n  gap: 7px;\r\n  box-sizing: border-box;\r\n  width: 104px;\r\n  padding: 5px 16px;\r\n  border-radius: 999px;\r\n  color: #fff;\r\n  background: rgba(13, 11, 20, 0.58);\r\n  backdrop-filter: blur(12px);\r\n  transform: translateX(-50%);\r\n  pointer-events: none;\r\n}\r\n\r\n#sl-speed-hint[hidden] {\r\n  display: none;\r\n}\r\n\r\n.sl-speed-hint-value {\r\n  font-size: 15px;\r\n  font-weight: 400;\r\n  line-height: 1;\r\n  letter-spacing: 0.02em;\r\n  font-variant-numeric: tabular-nums;\r\n}\r\n\r\n.sl-speed-hint-icon {\r\n  width: 16px;\r\n  height: 8px;\r\n  color: rgba(189, 164, 255, 0.8);\r\n  transform: translateY(1px);\r\n}";
    document.head.appendChild(style);
  }

  var host = window.StremioLightningHost || null;
  var log = window.StremioLightningLogger.bind("bridge.main");

  if (!host) {
    log.error(
      "[StremioLightning] host adapter not available - bridge not loaded",
    );
  } else {
    var ctx = {
      host: host,
      appWindow: host.window,
      webview: host.webview,
      pipFeatureOn: localStorage.getItem("sl-pip-feature") !== "false",
      shellTransport: null,
      initUpdateChecker: function () {},
    };

    log.info("[StremioLightning] Native player mode enabled (libmpv transport)");

    onDomReady(initCoreStyles);

    ctx.shellTransport = initShellTransport(ctx);
    ctx.shellTransport.observeMpvProperties();

    window.StremioEnhancedAPI = window.StremioEnhancedAPI || {};

    initExternalLinks(ctx);
    initShellDetection();
    initBackButton();
    initShortcuts(ctx);
    initPictureInPicture(ctx);
    initUpdateBanner(ctx);

    onWindowLoad(function () {
      ctx.initUpdateChecker();
    });
  }
})();
