// Generated by scripts/build-bridge.mjs.
// Source: web/bridge/src/main.js and styles.css.
// Other bridge modules are injected before this entrypoint by the native shells.
(function () {
  "use strict";

  function initCoreStyles() {
    var style = document.getElementById("sl-core-ui-styles");
    if (style) return;

    style = document.createElement("style");
    style.id = "sl-core-ui-styles";
    style.textContent = ".back-button-container-lDB1N svg {\n  filter:\n    drop-shadow(1px 0 0 rgba(15, 15, 25, 0.25))\n    drop-shadow(-1px 0 0 rgba(15, 15, 25, 0.25))\n    drop-shadow(0 1px 0 rgba(15, 15, 25, 0.25))\n    drop-shadow(0 -1px 0 rgba(15, 15, 25, 0.25)) !important;\n}";
    document.head.appendChild(style);
  }

  var host = window.StremioLightningHost || null;
  var log = window.StremioLightningLogger.bind("bridge.main");

  if (!host) {
    log.error(
      "[StremioLightning] host adapter not available - bridge not loaded",
    );
  } else {
    var ctx = {
      host: host,
      appWindow: host.window,
      webview: host.webview,
      pipFeatureOn: localStorage.getItem("sl-pip-feature") !== "false",
      shellTransport: null,
      initDiscordRpc: function () {},
      initUpdateChecker: function () {},
    };

    log.info("[StremioLightning] Native player mode enabled (libmpv transport)");

    onDomReady(initCoreStyles);

    ctx.shellTransport = initShellTransport(ctx);
    ctx.shellTransport.observeMpvProperties();

    window.StremioEnhancedAPI = window.StremioEnhancedAPI || {};

    initExternalLinks(ctx);
    initShellDetection();
    initBackButton();
    initShortcuts(ctx);
    initPictureInPicture(ctx);
    initDiscordRpcTracker(ctx);
    initUpdateBanner(ctx);

    onWindowLoad(function () {
      ctx.initDiscordRpc();
      ctx.initUpdateChecker();
    });
  }
})();
