[workspace]
members = [
    "crates/xtask",
    "crates/stremio-lightning-core",
    "crates/stremio-lightning-identity",
    "crates/stremio-lightning-linux",
    "crates/stremio-lightning-macos",
    "crates/stremio-lightning-windows",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
split-debuginfo = "packed"
