import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = resolve(root, 'web/bridge/src');
const outputFile = resolve(root, 'web/bridge/bridge.js');

const body = readFileSync(resolve(sourceDir, 'main.js'), 'utf8').trim();

const bundled = `// Generated by scripts/build-bridge.mjs.\n// Source: web/bridge/src/*.js.\n// Other bridge modules are injected before this entrypoint by the native shells.\n(function () {\n  "use strict";\n\n${body
  .split('\n')
  .map((line) => (line ? `  ${line}` : ''))
  .join('\n')}\n})();\n`;

writeFileSync(outputFile, bundled);
console.info(`Built ${outputFile}`);
