import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = resolve(root, 'web/bridge/src');
const outputFile = resolve(root, 'web/bridge/bridge.js');

const css = readFileSync(resolve(sourceDir, 'styles.css'), 'utf8').trim();
const main = readFileSync(resolve(sourceDir, 'main.js'), 'utf8').trim();
const styleLoader = `function initCoreStyles() {
  var style = document.getElementById("sl-core-ui-styles");
  if (style) return;

  style = document.createElement("style");
  style.id = "sl-core-ui-styles";
  style.textContent = ${JSON.stringify(css)};
  document.head.appendChild(style);
}`;
const body = `${styleLoader}\n\n${main}`;

const bundled = `// Generated by scripts/build-bridge.mjs.\n// Source: web/bridge/src/main.js and styles.css.\n// Other bridge modules are injected before this entrypoint by the native shells.\n(function () {\n  "use strict";\n\n${body
  .split(/\r?\n/)
  .map((line) => (line ? `  ${line}` : ''))
  .join('\n')}\n})();\n`;

writeFileSync(outputFile, bundled);
console.info(`Built ${outputFile}`);
